In [1]:
import numpy as np

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/julien/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julien/anaconda/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/julien/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julien/anaconda/include']
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/julien/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/julien/anaconda/include']
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/julien/anaconda/lib']
    define_macros = [('SCIPY

In [4]:
my_array = np.array([1,2,3,4,5])
my_list = [1,2,3,4,5]

In [8]:
# an and y are vectors
# numpy arrays are fixed-size (unlike Python lists)
# numpy arrays are homogenious: all elements are coersed to the 'highest" data type
x = np.array([1,2,3,4,5])
y = np.array([2.5,4.5,2,1,3])
np.dot(x,y)

36.5

In [9]:
z = np.array([0,1,2,3,4,'hello'])
z.dtype

dtype('<U21')

In [10]:
z2 = np.array([1,0,2,3,4,5,'hello i am a very large string'])
z2.dtype

dtype('<U30')

In [11]:
z = np.array([0,1,2,3,4,5.7], dtype='int64')
z

array([0, 1, 2, 3, 4, 5])

In [12]:
z = np.array([0,1,2,3,4,5.7], dtype='str')
z

array(['0', '1', '2', '3', '4', '5.7'], 
      dtype='<U3')

In [14]:
z = np.array([0,1,2,3,4,'hello'], dtype='int64')
z

ValueError: invalid literal for int() with base 10: 'hello'

In [15]:
x.shape

(5,)

In [17]:
x.size

5

In [18]:
x.ndim

1

In [19]:
a = np.array([2,3,4])
b = np.array([2.5,2,4])

In [20]:
x = np.array([[0,1],
             [5, 6]])

array([ 4.5,  5. ,  8. ])

In [22]:
arr = np.array([10,20,2,43,4,1,0,1,43])

In [24]:
arr[arr>9]

array([10, 20, 43, 43])

In [25]:
arr[(arr > 9) | (arr < 1)]

array([10, 20, 43,  0, 43])

In [26]:
arr[(arr < 9 ) | (arr % 2 == 0)]

array([10, 20,  2,  4,  1,  0,  1])

In [27]:
np.all(arr > 3)

False

In [28]:
np.any(arr > 3)

True

In [30]:
arr[[True,False, True, False, False, False, False, False, False]]

array([10,  2])

In [32]:
arr

array([10, 20,  2, 43,  4,  1,  0,  1, 43])

In [31]:
np.max(arr)

43

In [33]:
np.argmax(arr)

3